-- 코드를 입력하세요
SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
FROM REST_INFO R1

WHERE (
    SELECT R2.FAVORITES
    FROM REST_INFO R2
    WHERE R1.FOOD_TYPE = R2.FOOD_TYPE
    ORDER BY R2.FAVORITES DESC
    LIMIT 1
) = R1.FAVORITES
ORDER BY FOOD_TYPE DESC

# SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE