-- 코드를 입력하세요
SELECT RC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR RC
WHERE RC.CAR_ID IN (
    SELECT RH.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    WHERE DATE_FORMAT(RH.START_DATE, "%m") = '10'
)
AND RC.CAR_TYPE = "세단"
ORDER BY RC.CAR_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
# WHERE DATE_FORMAT(RH.START_DATE, "%m") <= '10'
# AND DATE_FORMAT(RH.END_DATE, "%m") >= '10'