-- 코드를 작성해주세요
SELECT SUM(GR.SCORE) as SCORE, EM.EMP_NO, EM.EMP_NAME, EM.POSITION, EM.EMAIL
FROM HR_DEPARTMENT DE JOIN HR_EMPLOYEES EM JOIN HR_GRADE GR
ON DE.DEPT_ID = EM.DEPT_ID AND EM.EMP_NO = GR.EMP_NO
WHERE GR.YEAR = "2022"
GROUP BY EM.EMP_NO
ORDER BY SCORE DESC LIMIT 1