-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", GF.BOARD_ID, "/", GF.FILE_ID, GF.FILE_NAME, GF.FILE_EXT)
FROM USED_GOODS_BOARD GB JOIN USED_GOODS_FILE GF
ON GB.BOARD_ID = GF.BOARD_ID
WHERE GB.VIEWS = (
    SELECT ugb.VIEWS
    FROM USED_GOODS_BOARD ugb
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY GF.FILE_ID DESC