SELECT FP1.CATEGORY AS C, FP1.PRICE AS P, FP1.PRODUCT_NAME AS PN
FROM FOOD_PRODUCT FP1
JOIN (
    -- 각 카테고리별 가장 높은 가격을 찾는 서브쿼리
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) FP2
ON FP1.CATEGORY = FP2.CATEGORY AND FP1.PRICE = FP2.MAX_PRICE
WHERE FP1.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY FP1.PRICE DESC;